### ISSUE TITLE
How to include only the database in the specified format in maxwell, such as mydb_*.*

### ISSUE THREAD

**Issue by yangzhongj** [zendesk/maxwell#1067]
How to include only the database in the specified format in maxwell, such as mydb_*.*？

**Comment by macboy012** [comment]
It's not quite clear to me what you're asking. I'm guessing your asking about only capturing changes which happen to a specific database, so that'd be documented in [filtering](http://maxwells-daemon.io/filtering/). From the 2nd example, I think you'd do `--filter = 'exclude: *.*, include: mydb_*'` but I haven't tried that myself.

**Comment by osheroff** [comment]
@macboy012 is almost right here.  you'll want to say `--filter = 'exclude: *.*, include: mydb.*'`  read more on the linked documentation for further questions.
