### ISSUE TITLE
[AliCloud] Maxwell 1.18.0 appear log event entry exceeded max_allowed_packet error

### ISSUE THREAD

**Issue by kevinclcn** [zendesk/maxwell#1118]
The detail log is 
```
log event entry exceeded max_allowed_packet; Increase max_allowed_packet on master; the first event 'mysql-bin.007035' at 854427386, the last event read from '/home/mysql/data3001/mysql/mysql-bin.007035' at 854427386, the last byte read from '/home/mysql/data3001/mysql/mysql-bin.007035' at 854427405.
```

After that binlog is disconnected and maxwell stops to do replication

**Comment by ericwush** [comment]
@jkrcma is this related to mysql config? 

@kevinclcn has the problem been resolved? If yes, how? Thanks

**Comment by jkrcma** [comment]
@ericwush Generally yes, but if you already have any replication setup running then this error message is not true, because no real slaves would be able to replicate from master if `max_allowed_packet` is at low value.

**Comment by kevinclcn** [comment]
@ericwush check this issue: https://github.com/zendesk/maxwell/issues/1088

**Comment by jkrcma** [comment]
@kevinclcn Unfortunately not the same use case, but I encountered mine today. So:

I found out that my error is only a consequence of #1129 and #1133. I have saved the Maxwell output as well as the whole binlog file, so I am willing to assist in further debugging.

@ericwush I can send you the output somewhere private and assist in searching for transactions in the binlog as it both of files may contain sensitive data.

**Comment by RamiFar** [comment]
This error is usually caused by a hardware glitch or a bug so vague that it hasn't been found in over a decade. The optimal solution that will definitely fix it without any risk of anomalies is to fully re-initialize the replication. You can do this without downtime or locking by using either `xtrabackup` or `mysqldump --single-transaction`.

Replication can be expensive if you have terabytes of data, so there may be a way you can restore replication without rebuilding the slave completely. You can use mysqlbinlog on the master to identify where the transaction is begin and look for near position 854427386 (your `Exec_Master_Log_Pos`). There is a very good chance that the position listed is actually has error and no transaction in the binlog starts at that position. You are also very likely to find that the coordinate distances between these transactions are nowhere near your max_allowed_packet value.

If that is the case, you can reset your replication coordinates on the slave to the last transaction mysqlbinlog lists that is before the position the slave thinks it is at. You can find more details on exactly what to do in this [MariaDB and MySQL troubleshooting](https://shatteredsilicon.net/blog/2022/05/22/fixing-error-1236-from-master-max_allowed_packet/) article.
