### ISSUE TITLE
Truncate row instead of discarding it if RecordTooLarge exception has occurred

### ISSUE THREAD

**Issue by dongxiaohe** [zendesk/maxwell#1122]
**Context:**
This is a feature request, if table is too large or Kafka broker side has some certain sized limited configuration, maxwell would continue to run by throwing RecordTooLarge exception. However, the message would be discarded.

**Suggested Solution:**

- It is better we have configured option to allow message can be truncated rather than dropped.
- Also, a flag to indicate the message is _truncated_ would be ideal as well.
- What does truncated db change json looks like, what field should be truncated, it should be still a valid Json, otherwise it would break consumer side.

**Comment by osheroff** [comment]
mmmmmm, sure, I can see this, but how do we go about choosing which field to truncate?  I'm also pretty sure that unless we knew the max-size of the kafka/kinesis/etc message we'd end up with out-of-order issues.  Or is there a way to pull it from the producer?

**Comment by osheroff** [comment]
> With Kafka, I don't think it's doable to pull this information on producer's side. Our best bet is probably the admin client API (i.e. adminClient.describeTopics(topicNames)) and yet I don't see the required info there.

Hmm, maybe we force the user to provide the limit with something like:
`--truncate_at=1000000`.  Note that this won't really account for compression, but hey, whatever.

**Comment by xuebingli** [comment]
That's a good idea. What do you think, @dongxiaohe?

**Comment by dongxiaohe** [comment]
so late for the discussion :( . 

@fsat @timbertson  what do you guys think about `--truncate_at=1000000`. :)

**Comment by timbertson-zd** [comment]
I was actually thinking the message would just be the primary key(s). It's less than might be useful, but it should be a simple distinction since maxwell already serializes the PK in the kafka message key.

Also with regard to ordering, we're thinking about putting it in a separate "dead letter" topic, which you'd pass as an option in order to enable this functionality. It's a little less elegant than having it inline, but the benefit is that it's not a breaking format change. It also means we can publish the information in response to a rejected error, so we don't have to decide when to reject messages ourselves.

Unfortunately this would make each producer responsible for implementing the dead letter logic. We could share the "generate a skeleton message" code, but there'd still be some producer-specific code in each case.

**Comment by osheroff** [comment]
we don't truncate, but we do have fallback topics now
