### ISSUE TITLE
DEFAULT_JDBC_OPTS Doesn't Apply - Producer still produces '0000-00-00'

### ISSUE THREAD

**Issue by rohitgcs** [zendesk/maxwell#1173]
Using Maxwell-1.19
According to the docs it says the zeroDate is handled - but in my producer to send data to ES (which will not accept zero dates) I see '0000-00-00' errors.
 
Any idea why that's happening? Do I need to do something else for it to work?

Thanks

**Comment by rohitgcs** [comment]
@osheroff okay, so just to clarify, what does the jdbc_options parameter currently do?

I'd be more than happy to submit a PR but would love to get some guidance if you could (Java isn't my preferred language so might take a while to get it out - but definitely interested!)

**Comment by osheroff** [comment]
well, it defines the jdbc_options, but the connections that use JDBC are not the ones that replicate -- so the `zeroDate` flag really would only affect bootstrapping or other operations that actually *use* jdbc.

the trick to honoring this would really be to tunnel a new flag in `MaxwellOutputConfig` down into the `asJSON` methods of `DateColumnDef` and `DateTimeColumnDef` that would cast bogus date-times as `null` instead of `0000-00-00`

**Comment by osheroff** [comment]
fixed in 1.19.4
