### ISSUE TITLE
Maxwell Used too many mysql connections

### ISSUE THREAD

**Issue by chengcxy** [zendesk/maxwell#1540]
I used maxwell docker images(zendesk/maxwell:latest) to  monitor mysql binlog to  rabbitmq
config.properties  like this
```
client_id=107_z_pe_z_pe_pe_company_shareholder_info
user=maxwell
password=mypassword
host=myhost
port=3306
schema_database=maxwell
producer_partition_by=primary_key
replica_server_id=28085
producer=rabbitmq
rabbitmq_host=myrabbitmq_host
rabbitmq_port=5672
rabbitmq_user=admin
rabbitmq_pass=myrabbitmq_pass
rabbitmq_virtual_host=/
rabbitmq_exchange=maxwell
rabbitmq_exchange_type=direct
rabbitmq_exchange_durable=true
rabbitmq_exchange_autodelete=false
rabbitmq_routing_key_template=%db%.%table%
rabbitmq_message_persistent=true
rabbitmq_declare_exchange=true
ignore_producer_error=false
metrics_prefix=pe_company_shareholder_info
metrics_type=http
metrics_http_port=28085
filter=exclude: *.*,include:z_pe.pe_company_shareholder_info
```

But when I creatd other maxwell docker containers(8 containers,one container monitor one table),I found the connections of mysql process become more and more

**Comment by chengcxy** [comment]
I modified config.properties  and run a docker container,Found the docker process add 10 connetions
![image](https://user-images.githubusercontent.com/25173362/87868642-a78f8900-c9ca-11ea-9088-6713b80fd5e4.png)

```
...
metrics_type=http
metrics_jvm=true
http_bind_address=localhost
http_port=28099
http_path_prefix=maxwell
http_diagnostic=true
http_diagnostic_timeout=10000
```

**Comment by stym06** [comment]
One Maxwell instance creates three connections; one for it's metadata (maxwell db), one for the source schema and most recent offset pull (SHOW MASTER STATUS) and one for replication, which is single-threaded.

**Comment by chengcxy** [comment]
> One Maxwell instance creates three connections; one for it's metadata (maxwell db), one for the source schema and most recent offset pull (SHOW MASTER STATUS) and one for replication, which is single-threaded.

Thanks. I have another question, if i used metrics_jvm and monoitor maxwell process by Http,the service of Web is created new connections?

**Comment by chengcxy** [comment]
I found the user(maxwell) of mysql  used connection is dynamic

The num of maxwell docker containers  in 172.31.128.130 is 4,But the num of mysql connections is 20

![image](https://user-images.githubusercontent.com/25173362/88040183-1d3a5700-cb7b-11ea-9e82-adbc5d5cbfcf.png)

mysql -query:
![image](https://user-images.githubusercontent.com/25173362/88040351-5a9ee480-cb7b-11ea-9fe5-5bea6c26c6a7.png)

**Comment by mpviau** [comment]
Yeah looks like someone hard coded the C3P0 connection pool size in the code.  The order of precendence is as follows according to C3P0 documentation:

1. Configuration values programmatically set.
2. Configuration values set in system properties.
3. Configuration values taken from the default configuration of a c3p0-config.xml file.
4. Configuration values specified in a c3p0.properties file
5. Configuration values in a c3p0.json file, if and only if Typesafe config libraries are available.
6. Configuration values in a c3p0.conf file, if and only if Typesafe config libraries are available.
7. Configuration values in a application.properties file, if and only if Typesafe config libraries are available.
8. Configuration values in a application.json file, if and only if Typesafe config libraries are available.
9. Configuration values in a application.conf file, if and only if Typesafe config libraries are available.
10. Configuration values in a reference.conf file, if and only if Typesafe config libraries are available.
11. c3p0's hard-coded default values.

Put otherwise, this prevents anyone to modify those settings except by modifying the code.

I just wonder how many connections Maxwell does really require? My guess is 1 for the binlog, 1 for the bootstrap according that you are running async.  What else am I missing?

**Comment by osheroff** [comment]
> I just wonder how many connections Maxwell does really require? 

It's a range. 

1.  For the binlog, though this is not pooled.
2. For bootstrapping.  
3. a connection that updates bootstrap statistics
4. a connection for the thread that updates maxwell.positions
5. for updating maxwell.schemas (including some long running operations like schema compaction)

There may be more but it looks like the range of 1-5 hard coded in the pool is about right; 99% of the time maxwell will use 1 or 2 connections.

**Comment by mpviau** [comment]
Actually turns out I was wrong.  C3P0 by default will not close any idle connections, so you can always set system properties, and the code only defines min and max pool size.  You can add other parameters anyway you want.  The easiest way I found was to add a JAVA_OPTS environment variable to my docker container so that c3p0 configs are passed as Java system properties like:

JAVA_OPTS="-Dc3p0.initialPoolSize=1 -Dc3p0.maxIdleTimeExcessConnections=5 -Dc3p0.maxIdleTime=30"

Those values are only useful for testing purposes, you will have to tweak for your situation,

**Comment by mpviau** [comment]
Thanks for your quick response on this @osheroff  

I'm using a split scenario, and I see around 5 connections maintained per Maxwell client on the replicated db host, I did not check the maxwell db host.

**Comment by chengcxy** [comment]
I used another method to handle this problem. 
in config.properties,we can set more table monitor like 
```
filter=exclude: *.*,include:z_pe.*,include:xx.*
```
not run more maxwell container to monitor different tables
