### ISSUE TITLE
How to handle the surge gracefully

### ISSUE THREAD

**Issue by jimymodi** [zendesk/maxwell#1576]
We are trying to find the best option to accommodate the huge surge created by a batch job. 
![image](https://user-images.githubusercontent.com/415224/92564068-38316980-f296-11ea-9a6c-8733d6c9b87f.png)
The above graph shows the kafka in rate for the topic. There is a surge of 35X. 
This maxwell instance is running in a container of 0.25 vcpu and 8GB of RAM. The base image used is `zendesk/maxwell:v1.19.6`.  
Below is the RAM and CPU usage pattern.
![image](https://user-images.githubusercontent.com/415224/92605647-97f83680-f2cf-11ea-919d-63f976a5d6a1.png)
![image](https://user-images.githubusercontent.com/415224/92605729-af372400-f2cf-11ea-9181-27cf48d471a2.png)
The spikes in CPU and MEM is noticed when the batch job adds the data. Now CPU comes down instantly as soon as producing of all binlog events is completed to kafka topic. However MEM takes 6-7 hours to come to normal range. Plus we also see a sudden drop in mem utilization at a point every day. I am still not able to attribute it to some event.

What we would like to understand is how to gracefully handle this surge. We do not mind it producing all the events takes more time ?
Why does MEM takes a long duration to come to normal levels and that too gradually. And not instantly as it spikes ?
Is it a good practice to run this two type of data stream (batch and continuous) within the same maxwell instance or use two separate instance for it ?
Would be great if anyone can give pointer to investigate it further.

**Comment by osheroff** [comment]
the way a JVM naturally handles memory is a weird thing, and once Maxwell is done with the memory there's no guarantee that it will be released back to the operating system in a timely fashion.  If you want insight into *just* what maxwell is doing you'd want to track internal JVM metrics about memory usage rather than system level metrics. 

Does the batch job create giant transactions?

The easiest fix here is to use `-xMx` to simply limit the max RAM footprint of a maxwell instance; you may sacrifice a tiny bit of performance and do more GCs during the batch process but I don't think it'd be a big deal.

**Comment by jimymodi** [comment]
Sure will try to get internal JVM metrics. 

Yes the batch job dumps around 2M records in just 2-3 minutes.

Will try the `-xMx`. By sacrificing performance do you mean the producing will be slow ?

**Comment by osheroff** [comment]
if the JVM has to run GC a lot it'll slow down a bit.  probably not that much though.

**Comment by osheroff** [comment]
Hi, I'm closing down old issues.  Please feel free to re-open this issue with more comments if you have them.
