### ISSUE TITLE
Backtracking master recovery

### ISSUE THREAD

**Issue by io41** [zendesk/maxwell#165]
From the docs...

> Currently Maxwell is not very smart about master recovery or detecting a promoted slave; if it determines that the server_id has changed between runs, Maxwell will simply delete its old schema cache and binlog position and start again. We plan on improving this situation in 0.12.

From the changelog I guess this hasn't changed yet. Are there any new targets for this? I presume it's still on the roadmap?

**Comment by osheroff** [comment]
@io41, yeah, it's still on the roadmap, but I don't have any official targets for it.  For some reason I must have thought there was a simple algorithm, but instead it turns out to be quite a bit of coding: There's a "simple" but inefficient method of jumping backwards through binlogs until you find the point at which one server took over from another, and a much more complicated but faster method involving always keeping "sync points" between master and slaves.  The situation will get much better in 5.7 with GTIDs, which is also on the ol' 'TODO' list.

There is a small feature I built that helps a bit here, which is that you can force Maxwell to start replicating at a particular position -- so if you know the first position of your new master, you can convince maxwell to start there.

I'll update the docs.

**Comment by io41** [comment]
Fantastic, thanks. Looking forward to seeing how to use that trick.

**Comment by bwilliams42** [comment]
@osheroff I am unclear about cluster set up. I don't see anything in the docs about how this works. Do you think you can shed some light on this please? Is there a maxwell "runbook" I can use as a reference?

**Comment by osheroff** [comment]
@bwilliams42 when you say "cluster setup" do you mean multiple maxwell processes, or allowing maxwell to continue on a promoted master?

**Comment by bwilliams42** [comment]
Opps..Sorry @osheroff i missed this. My aim is to run maxwell in production. So two things. 
 
1. I want to have it running in a master/slave(s) configuration. In the event of a failure it should seamlessly promote a new master from the available slave(s). 
 1. (Not related to this ticket, but i'll ask) I want to determine needed hardware resources. It would be good to have that in the docs.

**Comment by osheroff** [comment]
@bwilliams42 yeah, so I've avoided (thus far) putting any sort of clustering in maxwell.  At Zendesk we use hashicorp's [consul](https://www.consul.io/), and I run a few copies of maxwell that all compete for a distributed lock (using `consul lock`).  Works pretty good.  In theory it's something that could be baked into Maxwell (using a row in the database as a lock), but it feels... I dunno.  A bit ugly to build into maxwell.  

As far as hardware resources, yeah, would be nice to publish.  A lot depends on how many TPS you do in your cluster, but we run a pod (12 fusionIO db clusters) on about 8 cores and 16gb of ram.

**Comment by bwilliams42** [comment]
OK. Thanks for this bit of info @osheroff. i agree with you that the extra bit will make it ugly. But some support would be nice for the sake of seamless failover. I gotta get caught up on the code base, but i figure this may be a good way to do that..by diving in a helping out. Thanks again.

**Comment by osheroff** [comment]
sounds good @bwilliams42, see what you come up with.  There's a whole group of issues that could be tackled around running multiple copies of maxwell, not just for high availability but for different ways of presenting/partitioning the data

**Comment by osheroff** [comment]
maxwell 1.2.0 has support for backtracking recovery
