### ISSUE TITLE
Boolean field error on pubsub pusblisher

### ISSUE THREAD

**Issue by fernhtls** [zendesk/maxwell#1826]
**Problem**

On upgrading maxwell to version `v1.36.0` or `v1.37.0` we have encountered an error related to boolean fields.

Our maxwell configuration it's using GCP pubsub as the producer, and on one of the tables we have boolean fields.

On nullifying the boolean we noticed the following error:

```
Exception in thread "maxwell-pubsub-worker" java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3.isStringEmpty(java.lang.Object)'
	at com.google.pubsub.v1.PubsubMessage.getSerializedSize(PubsubMessage.java:519)
	at com.google.cloud.pubsub.v1.Publisher$OutstandingPublish.<init>(Publisher.java:570)
	at com.google.cloud.pubsub.v1.Publisher.publish(Publisher.java:246)
	at com.zendesk.maxwell.producer.MaxwellPubsubProducerWorker.sendAsync(MaxwellPubsubProducer.java:211)
	at com.zendesk.maxwell.producer.AbstractAsyncProducer.push(AbstractAsyncProducer.java:93)
	at com.zendesk.maxwell.producer.MaxwellPubsubProducerWorker.run(MaxwellPubsubProducer.java:188)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Maxwell seems to be still running, or hanging, but no further messages are received on the pubsub topic.

**Expected behaviour**

Maxwell should probably put the filed as null in it's payload, or even not include the field in the payload.

**Reproduce**

- Replicate table with null booleans to pubsub producer
- Use version `v1.36.0` or `v1.37.0`.
- Maxwell configuration used:
  ```
  replication_host=<REPLDB>
  replication_port=3309
  replication_user=<REPLUSER>
  replication_password=<REPLPASSWD>
  host=<HOST>
  port=3308
  user=<USER>
  password=<PASSWD>
  
  client_id=<CLIENT NAME>
  producer=pubsub
  log_level=info
  pubsub_project_id=<PROJECT_ID>
  pubsub_topic=<TOPIC>
  ddl_pubsub_topic=<DDL_TOPIC>
  filter=exclude:*.*, include:<TABLE WITH BOOLEAN>
  metrics_type=http
  output_ddl=true
  output_primary_keys=true
  output_primary_key_columns=true
  output_null_zerodates= true
  output_nulls=true
  buffer_memory_usage=0.50
  ```

**Comment by ragibsm** [comment]
The same error happens to me even if I don't have any boolean columns in the table. It seems that this error is not related just to boolean fields. In version v1.35.0 everything works fine, so this is probably a bug introduced in version v1.36.0. Can we expect this to be fixed any time soon?

**Comment by lpmarques** [comment]
As @ragibsm said, this is indeed not related to boolean columns in the table. It is probably affecting everyone that uses the pubsub producer from v1.36.0 beyond. After upgrading, this error occured for all tables that I tried and events stopped being produced.

Apparently, this is a bug related to a change in protobuf version from 3.13.0 to 3.16.1 (https://github.com/zendesk/maxwell/compare/v1.35.5...v1.36.0#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R281).

The reason seems to be that this method isStringEmpty() was added only in version 3.18 of protobuf and, before maxwell 1.36.0, maven was resolving dependency conflicts by opting on protobuf 3.18 or higher.

I found that another project had a similar problem and solved it by using protobuf 3.20.0:
https://github.com/camunda-community-hub/micronaut-zeebe-client/issues/88

@osheroff, can we count on you to take this fix to maxwell's next release and save us pubsub producer users?

**Comment by osheroff** [comment]
sure i can upgrade a library :)

**Comment by osheroff** [comment]
latest release upgrades the lib.  LMK how it goes.

**Comment by lpmarques** [comment]
For me it worked like a charm. Thank you!
