### ISSUE TITLE
why is recapture_schema does not default to true?

### ISSUE THREAD

**Issue by lenimartin** [zendesk/maxwell#1972]
Hi all,

I had a schema change and a column was added in the middle of the table.
As a result, in my JSON. Maxwell would put the wrong values in the keys.
Running Maxwell with --recapture_schema made it realise the order had changed and it started sending the correct fields again.
Now it works I removed it as I wonder what is the impact of it having it as in 1.16 release you said `flag for when ya wanna start over` which is not my understanding of what happened when I set it. Plus the fact that it defaults to false makes be believe I am missing something here and this behaviour is not clearly documented.

Is this flag just forcing a new valuation of the schema before it starts consuming the binlogs -> small delay -> default to false ?

Thank you

**Comment by osheroff** [comment]
maxwell by design should follow any schema changes as part of the replication stream.  If you encountered a situation where maxwell messed up the schema, log that as a bug.

Capturing a new schema on every start is incorrect behavior.  If a schema change happens while maxwell is stopped, recapturing when it boots will mean that the old binlog records will be played using the new schema, leading to errors.

**Comment by lenimartin** [comment]
okay thank you for the explanation.

In my case, maxwell was running (v1.37.0) and the offset of fields did not change, leading all json keys to contain the value from the previous field.

It happened a long time ago and maxwell was restarted without the flag a few time since and always came back with the wrong offsets.

I unfortunately can not provide you with logs to help understand/replicate the issue ...

Thanks you once again for the explanation
