### ISSUE TITLE
Partition imbalance

### ISSUE THREAD

**Issue by trulore** [zendesk/maxwell#355]
Hi!

We are using Maxwell, and we have a small issue with partitioning.  The primary keys of our tables do not hash very well (every key in the table starts with the same first 4 characters).  If you used our primary keys for hashing, you'd get major clumping, and that's what we are seeing with Maxwell.  It's not distributing the data evenly over the Kafka partitions for us.

So in the class MaxwellKafkaProducer.java, we replaced this line:

`ProducerRecord<String, String> record = new ProducerRecord<>(topic, this.partitioner.kafkaPartition(r, this.numPartitions), r.pkToJson(), r.toJSON());`

with this line:

`ProducerRecord<String, String> record = new ProducerRecord<>(topic, r.toJSON());`

and now Maxwell distributes across our Kafka partitions evenly.  Basically we let Kafka choose the partition rather than calculate one based on any characteristics of the data.

Is this worth pursuing as a feature or flag for Maxwell that would say "don't calculate partitions, let Kafka choose"?  I could create a pull request for the change if you think it's useful.

Thanks!  :)

**Comment by osheroff** [comment]
hmmm so with that config you're not sending keys at all to kafka, which iirc makes it randomly partitioned (or round-robin, I'd have to look).  That's a legit config, but you might be able to get similar results (and keep a primary key mapped to a partition with the command line flags `--kafka_partition_hash=murmur3`.  if that doesn't work to distribute evenly, I'd probably merge a PR with `--kafka_partition_by=random|roundrobin`.

Any chance you could dump a sample set of kafka keys that I could poke at?

**Comment by trulore** [comment]
Sure, here's the keys from one of the tables that was especially problematic.   You can see why these keys are not well suited to be hashes.  :)   It's an auto-incrementing key that's over 7 quadrillion by now....

7200102189523356
7200102189523357
7200102189523358
7200102189523359
7200102189523360
7200102189523361
7200102189523362
7200102189523363
7200102189523364
7200102189523365
7200102189523366
7200102189523367
7200102189523368
7200102189523369
7200102189523370
7200102189523371
7200102189523372
7200102189523373
7200102189523374
7200102189523375
7200102189523376
7200102189523377
7200102189523378
7200102189523379

...and so on and so on.

**Comment by osheroff** [comment]
@trulore, I went and dug into this more.  I ran a test in which I inserted 25k rows into a BIGINT auto_increment table, starting at 7200102189523356, producing into 95 partitions.  Here's what I found: 

With the native (naive?) hashing function (`--kafka_partition_by=primary_key`), distribution is not round-robin, but appears to tend towards uniform: the lowest count partition was within 4% of the messages of the highest count partition, with no apparent trend towards a long term bias

With murmur3 hashing, the distribution was actually significantly worse; the lowest-traffic partition received nearly 25% less traffic than the top partition.  cc @kristiankaufmann, that's not the greatest result.

Can you show me a repro of different results?

**Comment by trulore** [comment]
Well...we changed our config to kafka-partition-by=primary key, and kafka-hash-algorithm=default, and now we are seeing what you saw which is a nicely even load across the partitions.  

Unfortunately we didn't record exactly what our original config was that put us out of balance, because we tried a half-dozen configs early on, but maybe we were on a murmur3 config when things when out of balance.  Except what we saw was more than 25% out of balance.   But since we can't reproduce that right now, I'll have to chalk it up to Gremlins or user error.  :)

Everything is working great now, so thanks for your help walking us through this issue.  

This is quite a wonderful project that is really helpful to us for getting MySQL data into our live stream platform!

**Comment by osheroff** [comment]
glad to hear it @trulore.

**Comment by wushujames** [comment]
CC @ewencp. Ewen, you may find this interesting. @osheroff found that murmur3 gave imbalanced hashing on an auto-increment BIGINT column. Not sure how/if this affects https://github.com/confluentinc/kafka-connect-jdbc

**Comment by ewencp** [comment]
Kafka will round robin on *available* partitions (which should usually be all of them) if no key is provided (and if you're using the DefaultPartitioner, and of course I'm talking about the new producer). But obviously you can't do that if you want to include the primary key.

Given domain-specific knowledge (like PK where autoincrement will be common), a custom partitioner (i.e. the `primary_key` setting) is going to be most reliable since you know an autoincrementing ID will effectively just result in round robin but still result in semantic partitioning. That should of course lead to even distributions as long as you expect every key to appear with approximately the same frequency. (Hot keys can always cause hot partitions when using semantic partitioning) Using a generic hash function over the key bytes is just the best way to get something that should work ok without any additional info.

Might be worth pointing out that the default in Kafka's DefaultPartitioner is murmur2, not murmur3. I'm surprised murmur3 is doing so poorly given that smhasher is supposed to be a reasonably good evaluation. Would be interesting to see if murmur2 suffers from the same issue.
