### ISSUE TITLE
Contribution Questions and Build Instructions

### ISSUE THREAD

**Issue by mtfisher** [zendesk/maxwell#426]
Wanting to contribute some more producers to Maxwell. As it would give more options for people wanting to use Maxwell rather than Kefka or File output options there are currently.

Just wondering two things:
1. Is there a coding standard I should follow for the project?
2. Can you point me to a resource which provides instructions on how to get a Java dev and Build environment that will allow for me to contribute some more producers? It can be generic just as long as it would work for Maxwell.

**Comment by osheroff** [comment]
@mtfisher, 

1.  The only coding standard is tabs instead of spaces.  Follow existing indents and you'll be fine.

2.  You'll need:

- to clone the repo
- a working jdk get it from oracle
- optionally an IDE (intelliJ and eclipse will both work fine)

After you clone the repo, `make` will get you a compiled copy of maxwell.  `make test` will bootstrap its own binaries, but you'll of course need mysql running locally to run maxwell.

**Comment by mtfisher** [comment]
So the make script will deal with Maven for pulling in extra packages?
It's just not done any Java code for years and for the extra produces I would like to use some existing packages. So apologies for the dumb questions.

**Comment by osheroff** [comment]
yeah, there's a basic-clone of maven functionality so I don't have to deal with maven's slowness and hardness.  I do believe that `mvn test` and `mvn compile` are still functional though; maxwell uses a standard pom.xml in case you want to go that route
