### ISSUE TITLE
Intermittent concurrency issue while bootstrapping a large number of tables

### ISSUE THREAD

**Issue by bmichaud** [zendesk/maxwell#443]
We ran bootstrap on our entire database several times yesterday. Twice this happened. 

Problem: This terminates the bootstrap process intermittently. It appears to be a concurrency issue.
Version: Maxwell 1.2.1

15:35:58,847 INFO  MaxwellReplicator - async bootstrapping: replaying 15 skipped rows...
java.lang.NullPointerException
        at java.lang.String.compareTo(String.java:1155)
        at com.zendesk.maxwell.BinlogPosition.newerThan(BinlogPosition.java:55)
        at com.zendesk.maxwell.bootstrap.AsynchronousBootstrapper.replaySkippedRows(AsynchronousBootstrapper.java:131)
        at com.zendesk.maxwell.bootstrap.AsynchronousBootstrapper.completeBootstrap(AsynchronousBootstrapper.java:97)
        at com.zendesk.maxwell.bootstrap.AsynchronousBootstrapper.work(AsynchronousBootstrapper.java:172)
        at com.zendesk.maxwell.MaxwellReplicator.work(MaxwellReplicator.java:169)
        at com.zendesk.maxwell.RunLoopProcess.runLoop(RunLoopProcess.java:35)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:163)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:180)

Work-around was to simply restart Maxwell. This clears the table that failed, but the remaining records in the bootstrap table are ignored, so we had to mark those as completed and re-insert those last 23 records.

**Comment by osheroff** [comment]
if i'm reading the stack trace correctly, this means that the binlog position returned here:

https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/bootstrap/AsynchronousBootstrapper.java#L131

is invalid, and has no `binlog_file`.  

I think this could happen if you run a bunch of bootstraps back-to-back, and it finishes a whole table before the check here https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/bootstrap/SynchronousBootstrapper.java#L73 becomes true.   Does that jibe with your symptoms?  Was the table in question fairly small (capable of being bootstrapped in under 250ms)?  

cc @nmaquet

**Comment by nmaquet** [comment]
@osheroff I don't know how a `BinlogPosition` object can have a `null` `file` member, but I'm fairly confident that it's not related to `updateInsertedRowsColumn`. This method is there for convenience only, it allows the CLI to show progress information on the current bootstrap but has no other impact that I can see.

Do you have any idea why `BinlogPosition` could have a `null` `file` member?
Adding `assert(file != null);` to the `BinlogPosition` could help tracking down the root cause of this.

**Comment by osheroff** [comment]
check out `getBootstrapStartBinlogPosition` -- the position is pulled out of the `bootstrap` table  (https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/bootstrap/AsynchronousBootstrapper.java#L144)

**Comment by osheroff** [comment]
and no other place in the source code writes to the `binlog_file` field in the `bootstrap` table

**Comment by nmaquet** [comment]
@osheroff You're right! It's been a while since I've looked at this. The easiest fix I can see is to add 
`lastInsertedRowsUpdateTimeMillis = 0;`
here:
https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/bootstrap/SynchronousBootstrapper.java#L55
That will force `updateInsertedRowsColumn` to be called at least once.

If we want to make the fix more explicit, we can change the line
`if ( now - lastInsertedRowsUpdateTimeMillis > INSERTED_ROWS_UPDATE_PERIOD_MILLIS ) {`
to
`if ( insertedRows == 0 || now - lastInsertedRowsUpdateTimeMillis > INSERTED_ROWS_UPDATE_PERIOD_MILLIS ) {`

and move `++insertedRows;` down 2 lines.

**Comment by osheroff** [comment]
the first fix you describe is good by me.  you or me?

**Comment by nmaquet** [comment]
@osheroff I'll send you a PR in a few minutes, hang on.
