### ISSUE TITLE
Unexpectedly asked to create existing table

### ISSUE THREAD

**Issue by bmichaud** [zendesk/maxwell#487]
Could this error be a result of having two instances of Maxwell replicating on the same database node at the same time while a table called "mytable" is being created?

```
22:21:42,409 INFO  Maxwell - Maxwell v1.3.0 is booting (MaxwellKafkaProducer), starting at BinlogPosition[binarylog.000011:59239702]
22:21:42,526 INFO  OpenReplicator - starting replication at binarylog.000011:59239702
22:21:42,707 INFO  AbstractSchemaStore - Maxwell is capturing initial schema
com.zendesk.maxwell.schema.ddl.InvalidSchemaError: Unexpectedly asked to create existing table mytable
        at com.zendesk.maxwell.schema.ddl.ResolvedTableCreate.apply(ResolvedTableCreate.java:26)
        at com.zendesk.maxwell.schema.AbstractSchemaStore.resolveSQL(AbstractSchemaStore.java:58)
        at com.zendesk.maxwell.schema.MysqlSchemaStore.processSQL(MysqlSchemaStore.java:82)
        at com.zendesk.maxwell.replication.MaxwellReplicator.processQueryEvent(MaxwellReplicator.java:462)
        at com.zendesk.maxwell.replication.MaxwellReplicator.getRow(MaxwellReplicator.java:432)
        at com.zendesk.maxwell.replication.MaxwellReplicator.work(MaxwellReplicator.java:159)
        at com.zendesk.maxwell.util.RunLoopProcess.runLoop(RunLoopProcess.java:35)
        at com.zendesk.maxwell.Maxwell.start(Maxwell.java:160)
        at com.zendesk.maxwell.Maxwell.main(Maxwell.java:181)
22:21:49,319 INFO  Maxwell - starting shutdown
```

**Comment by osheroff** [comment]
it could be.  It could just be a simple race condition between the schema-capture code and the replicator; if `mytable` was created between `22:21:42` and 22:21:49`, that'd explain it pretty well; maxwell tries to capture its schema locklessly.

**Comment by bmichaud** [comment]
The script was run around 08:46:00 It was indeed during replication, though.

**Comment by osheroff** [comment]
oh, I see.  Yeah, you probably left the old `maxwell`.`positions` row in place, which meant that maxwell travelled back in time and tried to re-process DDL statements that were already represented in the captured schema, leading to this error.

So I think this issue is a secondary issue from a bad position... maybe #489 is, too?  What was the time progression of the 3 issues?

**Comment by bmichaud** [comment]
On 11/18/2016, #488 Happened first, as the DDL script was executing at 08:46:03, then this error happened at 22:21:42, probably on the same date. The third issue, #489, happened days later on 11/21/2016 at 09:24:38 when I wasn't around and my colleagues tried to "reanimate" Maxwell, but were unsuccessful. From the looks of the logs, #489 was concurrent replication and schema-capture like this one.

**Comment by osheroff** [comment]
can you get more details on what was done before #489 triggered?  Was it the same thing where the schema tables were truncated but the position was left behind? 

so correct me if I'm wrong:

- 11/18 0800 hit the PK column bug.  maxwell stops.
- 11/18 2200 TRUNCATE TABLE `schemas` -- hit #487
-  then what?  did you get maxwell going again?  how?
- 11/21 0900  your colleagues attempt to "reanimate" maxwell -- how had it stopped?

At the very least I will turn this into a story about a command-line flag that will wipe out all saved schema state and start over, something like `bin/maxwell --reset-stored-schema`.

**Comment by bmichaud** [comment]
> - 11/18 0800 hit the PK column bug. maxwell stops.
correct
> - 11/18 2200 TRUNCATE TABLE schemas -- hit #487 
The following tables were truncated:
- `tables`
- `schemas`
- `databases`
- `columns` 

> - then what? did you get maxwell going again? how?

Maxwell failed almost immediately with the errors shown above in issue #487

- 11/21 0900 your colleagues attempt to "reanimate" maxwell -- how had it stopped?

I will find out, but my strong suspicion is that it had not been successfully started again since it failed on 11/18 in the morning. Additionally, I will find out if they truncated all the above tables plus the positions table, which is entirely possible.

**Comment by osheroff** [comment]
> my strong suspicion is that it had not been successfully started again since it failed on 11/18 in the morning. 

Ok, I think this is *all* fallout then from the PK-rename bug and the truncation of tables.

**Comment by bmichaud** [comment]
What, then, should we do the next time Maxwell crashes? This is a fairly common occurrence, so wouldn't it make sense to have a safe way to restart it when DDL statements may have happened in the meantime? 
Is there a way, for example, to redo schema-capture without replication turned on, then start replication? 

Additionally, what is the best way to reposition the binlogs if the last known position has been deleted? What we generally do is delete the position, and re-bootstrap. 

We fought hard in our organization to lengthen the time period that binlogs are kept from 15 minutes to 3 hours, and we are trying to set up an auto-restart mechanism, but if you have utilities or procedures for proper recovery operations, please point me in the right direction. 

Thanks for your help.

**Comment by osheroff** [comment]
> This is a fairly common occurrence

I will endeavour, with all my power, to make it not so :)

> wouldn't it make sense to have a safe way to restart it when DDL statements may have happened in the meantime?

If maxwell can't process DDL, things get pretty dicey.  The only 100% safe thing to do here is to clear out the old position *and* schema, and restart maxwell from "now": if you can't process a DDL statement, there's no way to know which schema to correlate a row event to, so the old position (before the DDL statement) is largely trash. 

What I may finally do is to do a kludgy workaround in which I rescue the ddl error and try to proceed anyway by immediately re-capturing the schema.  I 100% hate this option, as it means I won't get bug reports on the errors anymore (and it's some kind of admission of failure), but I will probably just bite said bullet and write it. 

> Should only one Maxwell client do schema-capture, then start all of them for replication? 

Yes, that's best for now; in the future we should put some co-ordination logic in around multi-clients so that they can all start simultaneously.

> Additionally, what is the best way to reposition the binlogs if the last known position has been deleted? What we generally do is delete the position, and re-bootstrap.

That's fine if you can guarantee that no DDL statements have happened in the missing section of binlogs.  If there could be DDL in the missing binlogs, get rid of maxwell's copy of the schema, too.

**Comment by osheroff** [comment]
I'm going to close this as it was all a result of trying to fix a position by hand after encountering a separate maxwell error.  There's still a set of fixes owed somewhere around here on trying to recover somehow after a disaster, but it's unclear to me exactly what.
