### ISSUE TITLE
monitoring

### ISSUE THREAD

**Issue by smferguson** [zendesk/maxwell#536]
how do you guys ensure a specific maxwell process is healthy?

**Comment by osheroff** [comment]
we have a consumer application that sends stats to datadog, tagging the metrics per cluster of servers as well as per database/table, and then we create datadog monitors based upon that.  It's not a 100% solution as inactivity on the servers can lead to false positives, but I'm more-or-less of the philosophy that one should monitor the side-effects of an application rather than simply checking to see if a process is alive. 

There's another approach, which is to simply check `last_heartbeat_read` in `maxwell.positions` as well as `heartbeat` in `maxwell.heartbeats`.  As long as there's activity on a server, these timestamps should indicate maxwell's liveness.  Would gladly accept a simple program that outputs a status for maxwell based on these, if you found it useful.  

Of course, there's the heavier approach of opening up stats or JMX or a webserver or what have you, and if someone wants to take that task, cool, but those my thoughts on quick-and-dirty monitoring.

**Comment by smferguson** [comment]
So far I've just implemented a simple (separate) process that checks maxwell's position vs master and outputs that to datadog. GTK a little more about what you guys do. Thanks!
