### ISSUE TITLE
Add support to Kinesis Firehose

### ISSUE THREAD

**Issue by carlos-eduardo-gb** [zendesk/maxwell#544]
Makes sense add support for Kinesis Firehose? Amazon is adding a lot of functionalities for data processing via Lambda and automatically adding the raw data buffered and condensed to S3 (GZIP or Snappy), reducing a lot of boilerplate.

I don't know if this make sense to Maxwell, but in my opinion is a good feature.

**Comment by osheroff** [comment]
@thomasdziedzic can you comment here?  Not sure what-all is required for firehose separate from kinesis streams.

**Comment by thomasdziedzic** [comment]
I wasn't too familiar with firehose so I did some investigation and here is what I found.

Amazon provides an agent for firehose which reads files and sends them to firehose.
http://docs.aws.amazon.com/firehose/latest/dev/writing-with-agents.html

Maxwell has a file producer:
https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/producer/FileProducer.java

This integration should theoretically be possible already. I haven't verified this myself.

As it turns out, I didn't know that kinesis streams also had a similar agent:
http://docs.aws.amazon.com/streams/latest/dev/writing-with-agents.html

So it seems my PR was to build a native integration between maxwell and kinesis streams, but it was already theoretically possible. I wonder when they added these agents.

I guess this request boils down to:
1. Is the integration already possible using the agents that aws provides?
2. If it does, do we still want a native integration to send data to firehose?

I suspect that the firehose api will be identical to the streams api and since my PR already did all the necessary refactoring, it might be as simple as copying some code and replacing the api calls from streams to firehose.

**Comment by osheroff** [comment]
saw this:

> The method for generating the partition key. Valid values are RANDOM (randomonly generated integer) and DETERMINISTIC (a hash value computed from the data).  Default: RANDOM

so at least the native streams producer has that going for it over the file + agent approach.  If api-based firehose support looks trivial, I'd say go for it.  If people have the agent already running to gobble logs or whatever, we can point them to the file producer, although the docs seem to hand wave a bit of the log-rotation details away; maxwell would need copy/truncate semantics.

**Comment by alejobs** [comment]
Hi,

As far as I am concerned, Kinesis Firehose is designed to be linked to a kinesis stream, so that all events sent to a stream are finally saved on to an S3 bucket, Redshift table or ElasticSearch index. So in this case, one can go with the kinesis producer that we already have.

**Comment by carlos-eduardo-gb** [comment]
Ok, but this is what we have tried:

`docker run -it --rm -v `pwd`/.aws:/root/.aws --name maxwell osheroff/maxwell sh -c 'cp /app/kinesis-producer-library.properties.example /app/kinesis-producer-library.properties && echo "Region=us-east-1" >> /app/kinesis-producer-library.properties && echo "CustomEndpoint=firehose.us-east-1.amazonaws.com" >> /app/kinesis-producer-library.properties && bin/maxwell --user=maxwell --password=XXXX --host=XXXX --producer=kinesis --kinesis_stream=contracts --include_tables=contracts`

And this is the error:

```
20:52:10,048 WARN  LogInputStreamReader - [2017-01-24 20:52:10.048676] [0x0000001f][0x00007f169d6c5700] [warning] [AWS Log: WARN](AWSErrorMarshaller)Encountered AWSError
ResourceNotFoundException
Stream contracts under account 744617668409 not found.:

20:52:10,119 WARN  LogInputStreamReader - [2017-01-24 20:52:10.119041] [0x0000001f][0x00007f169d6c5700] [warning] [AWS Log: WARN](AWSErrorMarshaller)Encountered AWSError
ResourceNotFoundException
Stream contracts under account 744617668409 not found.:

20:52:10,189 WARN  LogInputStreamReader - [2017-01-24 20:52:10.189002] [0x0000001f][0x00007f169d6c5700] [warning] [AWS Log: WARN](AWSErrorMarshaller)Encountered AWSError
ResourceNotFoundException
Stream contracts under account 744617668409 not found.:
```

The service firehose also used a different endpoint like described in [documentation](http://docs.aws.amazon.com/general/latest/gr/rande.html#fh_region):

> firehose.us-east-1.amazonaws.com

The [implementation](http://docs.aws.amazon.com/firehose/latest/dev/writing-with-sdk.html) of API using firehose is different too.

I'm not an expert in maxwell arch, but looking the code and accordling @thomasdziedzic  i suppose the needed to create a MaxwellFirehoseProducer in MaxwellKinesisProducer using the API for Firehose. Is it make sense?

**Comment by alejobs** [comment]
Hi @carlos-eduardo-gb,

No, that was not what I was trying to say. You have different alternatives for "glueing" a Kinesis stream to a Firehose delivery stream:

1. Use Kinesis Analytics to get data from the kinesis stream and send it to firehose. Cons: you must define a schema beforehand, so if your stream has a dynamic schema this may be a problem.
2. Use a Lambda function to get data from kinesis stream and send it to firehose. You have some examples on github: https://github.com/awslabs/lambda-streams-to-firehose, https://github.com/awslabs/aws-big-data-blog/tree/master/aws-blog-firehose-lambda/kinesisFirehose (although they are not perfect, must be reviewed)

Appart from that, you also could:

- Develop a MaxwellFirehoseProducer as you mentioned, so that Maxwell directly sends events to Firehose. Be careful because delivery streams don't scale like kinesis streams. If you want to increase its limits you have to request it to AWS: http://docs.aws.amazon.com/firehose/latest/dev/limits.html
- Run AWS Kinesis Agent to get Maxwell events from a file (using Maxwell FileProducer). Be careful because Maxwell doesn't automatically rotate files, so you can end up with the disk full. Also, as they are two independent processes, you add an extra layer of failure (Maxwell can't guarantee that produced events get sent to Firehose). More info on: http://docs.aws.amazon.com/firehose/latest/dev/writing-with-agents.html

I hope this helps you.

**Comment by alejobs** [comment]
Hi @carlos-eduardo-gb ,

Just here to say that since august you can automatically "glue" an Amazon Kinesis Firehose stream with a Kinesis Stream, so that you don't have to deploy a Lambda or Kinesis Analytics app. See: https://forums.aws.amazon.com/ann.jspa?annID=4904
