### ISSUE TITLE
Feature request / discussion: embedded mode

### ISSUE THREAD

**Issue by geoff-addepar** [zendesk/maxwell#634]
This is the sort of thing I would normally post on a mailing list, but I can't find one, so it's going in the bug tracker. :)

I'm wondering if it's possible to run Maxwell embedded inside another java application. And if that's not currently an option, if me and my team developed that ability, we would like to know whether or not it might be accepted upstream. Besides being able to run embedded, we would also like to be able to customize (at least) the producer's behavior, and I believe an embedded mode would allow for other useful extension points like more sophisticated message filtering, topic name transformations, custom metrics reporters, etc.

At a code level, I'm thinking this would involve some refactoring of Maxwell, MaxwellContext, and MaxwellConfig, but nothing would end up being too invasive. The code is already fairly modular, so I don't think it would be all that much work. In the end, I picture it being like the Apache HttpComponents' HttpClientBuilder, where you use a builder pattern to tie all of Maxwell's components together and allow custom code to override/configure the various pieces. Where this might fall apart is if Maxwell uses any static state, system properties, or anything like that. (I do see some logger configuration in a static init block; that might need a small tweak.)

We have two main motivating factors. One is a simplified development process for our application, where we won't have to make all our developers install and configure Maxwell and Kafka. People can just run a single application JAR and have everything come up in an embedded mode (we would also use an embedded message queue), though we would probably separate things out onto different machines when running on production. The other main factor is that we want to introduce custom behavior into the message producer (e.g. a standard message header for all messages in our environment) and we think the easiest way would be to pull Maxwell in as a maven dependency and configure it in our code.

Does the Maxwell team have any thoughts on this approach? Has it been considered or done before?

**Comment by timbertson** [comment]
Seems reasonable to me - it's not a high priority for us, but as long as it's not invasive then making sure maxwell is modular is a good goal. 

@osheroff do you have strong opinions on forcing config to happen via properties (e.g. specifying names of classes) vs runtime-only config (allowing people to pass actual classes / instances)?

I expect it could get painful to have to maintain two configuration mechanisms, so perhaps try to deviate as little as possible from the existing MaxwellConfig (i.e. prefer putting things in there rather than separate APIs which are only available in embedded mode).

**Comment by osheroff** [comment]
Maxwell should be *mostly* usable as a JAR right now.  The build pipeline isn't setup to auto-publish the jar artifacts to maven, but there's some there.  

In my mind we'd solve 99% of people's problems by simply allowing folks to instantiate custom producer instances which get passed directly in via a `MaxwellConfig` object.  It's far and away the most common place people want to do something custom, ie field filtering, scrubbing, all that stuff.  

doing lots of code upheaval in other areas probably falls under the YAGNI principle, but I could be convinced otherwise if there was a real use case.

Do not go down the route of specifying names of classes.  Fuck that.

**Comment by Buktoria** [comment]
That being said, what would you recommend for those of us who want to implement a custom producer interface? Yes Maxwell currently supports mainstream publishing interfaces, but I seek to do something a bit more custom (specifically an HDFS writer). Right now I would need to fork the repo and make changes. 

I would argue that publishing maven packages would make writing custom producers for individuals much easier to maintain, then a fork of the entire project. I want to keep my customizations separate, and be able to easily get new Maxwell updates. 

Everyones use case is different, even if most people are using this for some sort of ETL pipeline. For example I want to be able to ignore tables because of various business reasons, and control the file structure data gets written with my HDFS producer. Maintaining my changes and your gets very difficult without an embedded mode.

The last maven Maxwell release was [1.8.0](https://mvnrepository.com/artifact/com.zendesk/maxwell/1.8.0). Would it be possible to at least publish the latest one, which has `ProducerFactory` implemented. This would make writing custom producers a lot easier.

**Comment by osheroff** [comment]
Yup, we’ve been lax about publishing to the maven repo.  Will see about integrating it into the release scripts.

**Comment by osheroff** [comment]
this was fixed long ago
