### ISSUE TITLE
Cannot trigger bootstrap if use different 'schema storage host' and 'replica host'

### ISSUE THREAD

**Issue by wangzw** [zendesk/maxwell#645]
If schema storage host is not the same as replica host,  `maxwell-bootstrap` command line report `Table does not exist` since it try to find table on schema host.

After insert a tuple in to bootstrap table `insert into maxwell.bootstrap (database_name, table_name) values ('xxx', 'xxx');`. Bootstrapping is not triggered. It seems that bootstrapping  is only triggered by an event on table `bootstrap`. But maxwell does not listen on schema storage host.

**Comment by osheroff** [comment]
yeah, this is a known deficiency.  I would, I think, accept a PR that changed how maxwell triggers bootstraps; instead of watching the replication stream, I think it should probably just poll the `maxwell.bootstraps` table periodically, starting and stopping bootstraps as it sees rows appear there.  @nmaquet and I went back and forth a bit on this one in the original design; I can't recall now whether there were strong arguments for the current design over a polling-based one.

**Comment by wangzw** [comment]
I have a pull request to fix this issue.

**Comment by wangzw** [comment]
I have merged master and pass all tests.

**Comment by pjebs** [comment]
Is there any reason why this fix hasn't been merged? @osheroff

**Comment by osheroff** [comment]
There's been a couple of attempts to fix this.  The simple PR referenced here doesn't really feel correct: it just inserts data into the replication connection.

There was another PR attempted somewhere but the author dropped it after some time.  I'm myself working slowly towards a solution.

**Comment by aladine** [comment]
I see this issue has been a long time. Is this issue resolved now in the latest release. I saw a note in v1.22.0

> Bootstrapping has been reworked and is now available in all setups, including those in which the maxwell store is split from the replicator.

**Comment by pjebs** [comment]
It would be amazing to resolve this issue. Its a real limitation.

**Comment by mengzhongtian** [comment]
when can fix it...

**Comment by liquidgenius** [comment]
Experiencing the same issue on Maxwell v1.22.3.

**Comment by osheroff** [comment]
this has been fixed in recent(ish) maxwells, we/I finally removed the old replica==bootstrap host requirement.
