### ISSUE TITLE
Do you have any tools parse insert,update,delete operation to sql?

### ISSUE THREAD

**Issue by AlvinYang-2017** [zendesk/maxwell#658]
Do you have any tools parse  insert,update,delete operation to sql?

thanks

**Comment by timbertson** [comment]
Do you mean that you would like maxwell to generate SQL instead of JSON? If so then no, there's no functionality for doing that. It sounds a bit like statement based replication, which is something mysql can already do (but which isn't very useful for consumers who aren't SQL databases).

**Comment by AlvinYang-2017** [comment]
ok ,I understand what you mean，thanks。

**Comment by osheroff** [comment]
when I first wrote Maxwell it had some functionality for transforming the binary logs directly back into SQL -- the first application did something like that.  It could be resurrected so that maxwell could directly output SQL instead of JSON, but it'd take some work.  If you look here: 

https://github.com/zendesk/maxwell/blob/master/src/main/java/com/zendesk/maxwell/schema/columndef/IntColumnDef.java#L45

you'll see that there's still sort of support for transforming column values into SQL, and the code for generating SQL is around in the source tree history somewhere.

**Comment by songxin1990** [comment]
Thanks.
