### ISSUE TITLE
Can Maxwell cluster?

### ISSUE THREAD

**Issue by jayws** [zendesk/maxwell#671]
Can Maxwell cluster? thanks!

**Comment by timbertson** [comment]
You mean multiple processes replicating the same database cluster? Not natively, no (a maxwell process needs to read every message to maintain ordering and schema consistency).

You could possibly achieve this by giving multiple maxwell processes different client IDs, and then using a database blacklist / whitelist to ensure each process handles a subset of your tables. For the most part one maxwell process is enough though.

**Comment by luyee** [comment]
how to impl HA or standby?

**Comment by timbertson** [comment]
Can you describe what you mean more specifically? As it stands, maxwell will pick up from the binlog location it last processed after shutting down, resulting in no missed messages. With the `ignore_producer_error` flag, maxwell will also terminate on a publisher error, ensuring at least once delivery.

**Comment by sanguinar** [comment]
I also face this question. Maxwell is excellent and we want use it in product environment. Then we must make it robust. The machine which run maxwell may crash and we hope to impl maxwell HA or standy to ensure that there is one maxwell work, rather than restart maxwell by manual operation.
Now we use keepalived  to impl mysql standy. Maxwell point to the VIP of mysql and Maxwell need not to switch mysql IP(Maxwell will crash while mysql VIP switch the real mysql ip. So I run a script to restart maxwell after 30s.). So how can we ensure or impl maxwell HA or standy.
@timbertson Any help of you is appreciated. thanks!

**Comment by sanguinar** [comment]
#802
