### ISSUE TITLE
GTID support

### ISSUE THREAD

**Issue by akshayi1** [zendesk/maxwell#69]
Is there a planned release for supporting replication based on the GTID, as opposed to the position, which I believe is the implementation that is currently existing?

**Comment by akshayi1** [comment]
Got your answer of it not being implemented in the near-future. Thanks! Closing it now.

**Comment by osheroff** [comment]
I'll leave this open, in case anyone else comes to want GTID.

**Comment by akshayi1** [comment]
Out of curiosity, I looked at open-replicator, and it looks like GTID is implemented there. Can you please clarify then why you said that it'll be quite a bit of work down in open-replicator? Am I looking at the wrong thing in open-replicator, or is it just that the boilerplate is present, but actual implementation is a lot more work? I'm just a little confused. Thanks!

**Comment by osheroff** [comment]
not as far as I can tell.  There's some support for parsing GTID
*events* from the logs, but there's no support for setting up GTID
replication positions (which are fundamentally different beasts than
file/position based replication positions)

**Comment by rtorrero** [comment]
Like someone already said on #251 this, combined with consul lock would improve a lot the HA of maxwell. Another instance could be on hold, resuming exactly where the first one left as soon as it fails.

**Comment by osheroff** [comment]
@rtorrero yup.  Been looking into maybe porting maxwell over to https://github.com/shyiko/mysql-binlog-connector-java for its GTID support, but it's a large-ish effort.

**Comment by smferguson** [comment]
bump. any word here? (feeling like it's stale) ... wondering if anyone runs maxwell with 5.7 in prod (without gtids)

**Comment by yogiGueta** [comment]
Is there any way to get the xid number of the transactions ordered? like if i have two mariadb clients writing  to mariadb, sometimes i got the xid in maxwell not in the right order....like:
2017-02-01 17:24:02.557 [main] INFO : {"database":"DB0","table":"T0","type":"update","ts":1485962642,"**xid**":2452507,"data":{"id":219499,"F0":437933182,"F1":15432081,"F2":453857335,"F3":1963974132},"old":{"F1":1601269758,"F2":1394049406}}
2017-02-01 17:24:02.560 [main] INFO: {"database":"DB0","table":"T0","type":"update","ts":1485962642,"**xid**":2452507,"data":{"id":244946,"F0":1226648266,"F1":530254919,"F2":1841928968,"F3":528578396},"old":{"F0":1400441802,"F1":719180255,"F2":769416959,"F3":223175808}}
2017-02-01 17:24:02.561 [main] INFO :{"database":"DB0","table":"T0","type":"update","ts":1485962642,"**xid**":2452507,"data":{"id":183584,"F0":779004500,"F1":1753604934,"F2":1618632991,"F3":1124771345},"old":{"F0":1398288673,"F1":1799403100,"F2":1641979330,"F3":592561791}}
2017-02-01 17:24:02.581 [main] INFO:  {"database":"DB0","table":"T0",**"type":"update"**,"ts":1485962642,**"xid":2452507**,"commit":true,"data":{"id":197743,"F0":663913596,"F1":1488959783,"F2":1712400104,"F3":10388106},"old":{"F0":2040813092,"F1":337639973,"F2":546838057,"F3":2054566224}}
2017-02-01 17:24:02.872 [main] INFO: {"database":"DB0","table":"T0"**,"type":"delete"**,"ts":1485962642,**"xid":2452499**,"data":{"id":253688,"F0":1660559508,"F1":773498766,"F2":1777714247,"F3":240264446}}
so there is a way to prevent it without gtid? using xid??

**Comment by osheroff** [comment]
I think the xid is dependent on when a transaction starts, not commits; so the ordering is not guaranteed like that.  The ordering of updates *is* properly serialized though.  You could use the Kafka offset of the message if you need something monotonic.

**Comment by yogiGueta** [comment]
can you elaborate please on how can i do it using offset? do you know mybe
if gtid also depend on transaction start?
thanks!

On Feb 1, 2017 9:59 PM, "Ben Osheroff" <notifications@github.com> wrote:

I think the xid is dependent on when a transaction starts, not commits; so
the ordering is not guaranteed like that. The ordering of updates *is*
properly serialized though. You could use the Kafka offset of the message
if you need something monotonic.

> On Feb 1, 2017, at 09:59, yogiGueta <notifications@github.com> wrote:
>
> Is there any way to get the xid number of the transactions ordered? like
if i have two mariadb clients writing to mariadb, sometimes i got the xid
in maxwell not in the right order....like:
> 2017-02-01 17:24:02.557 [main] INFO : {"database":"DB0","table":"T0"
,"type":"update","ts":1485962642,"xid":2452507,"data":{"id":219499,"F0":
437933182,"F1":15432081,"F2":453857335,"F3":1963974132},"
old":{"F1":1601269758,"F2":1394049406}}
> 2017-02-01 17:24:02.560 [main] INFO: {"database":"DB0","table":"T0"
,"type":"update","ts":1485962642,"xid":2452507,"data":{"id":244946,"F0":
1226648266,"F1":530254919,"F2":1841928968,"F3":528578396},"
old":{"F0":1400441802,"F1":719180255,"F2":769416959,"F3":223175808}}
> 2017-02-01 17:24:02.561 [main] INFO :{"database":"DB0","table":"
T0","type":"update","ts":1485962642,"xid":2452507,"data":{"id":183584,"F0":
779004500,"F1":1753604934,"F2":1618632991,"F3":1124771345},"
old":{"F0":1398288673,"F1":1799403100,"F2":1641979330,"F3":592561791}}
> 2017-02-01 17:24:02.581 [main] INFO: {"database":"DB0","table":"T0"
,"type":"update","ts":1485962642,"xid":2452507,"commit":true,"data":{"id":
197743,"F0":663913596,"F1":1488959783,"F2":1712400104,"
F3":10388106},"old":{"F0":2040813092,"F1":337639973,"F2"
:546838057,"F3":2054566224}}
> 2017-02-01 17:24:02.872 [main] INFO: {"database":"DB0","table":"T0"
,"type":"delete","ts":1485962642,"xid":2452499,"data":{"id":253688,"F0":
1660559508,"F1":773498766,"F2":1777714247,"F3":240264446}}
> so there is a way to prevent it without gtid? using xid??
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zendesk/maxwell/issues/69#issuecomment-276764617>, or mute
the thread

**Comment by osheroff** [comment]
when you receive the message in your kafka consumer it will have an `offset` property that you can access.  

GTIDs should be monotonic for a particular server, I think.  Maybe @HenryCaiHaiying can confirm, he's working on maxwell support for them currently.

**Comment by HenryCaiHaiying** [comment]
In the normal situation, GTID should be increasing on a particular server since it's composed of server-uuid:local-tx-id.  However there are two modes I haven't really tested it:

1. When you replicate binlogs from server A to server B, you can use multi-threaded mode, so it's possible that some threads on B will fetch later binlogs from A first, but I think the binlog apply should still keep the original order;
2. If you setup A as master and B as slave, later A crashed, the cluster failed over to B.  And later A recovered, A resumes as master.  I am not sure whether the new GTIDs issued from A will have a gap or not.

**Comment by yogiGueta** [comment]
Thank you @osheroff and @HenryCaiHaiying.
@HenryCaiHaiying how can i use your maxwell version?

**Comment by w7089** [comment]
It would be really helpful to have gtid support. Is there a version of maxwell in github that supports it?

**Comment by w7089** [comment]
@HenryCaiHaiying Does GTID parsing feature you added support MariaDB?
We saw [here](https://mariadb.com/kb/en/mariadb/gtid/#gtid_strict_mode) the following remark:
_Note that MariaDB and MySQL have different GTID implementations, and that these are not compatible with each other._

**Comment by yogiGueta** [comment]
I try to run your project with GTID support, but somthing is not right: the "gtid_set" colunm inside table positions is always null and never change...

**Comment by HenryCaiHaiying** [comment]
That's a bit weird, did you turn on shyiko_mode and other mysql settings as I mentioned in readme file?

**Comment by HenryCaiHaiying** [comment]
For MariaDB, I don't know whether it will work or not.  We are using shyiko's binlog connector, if his connector can support mariadb, we might be fine.

**Comment by yogiGueta** [comment]
Yes for mysql settings, what do you mean by shyiko-mode?
On Feb 2, 2017 8:55 PM, "Henry Haiying Cai" <notifications@github.com>
wrote:

That's a bit weird, did you turn on shyiko_mode and other mysql settings as
I mentioned in readme file?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zendesk/maxwell/issues/69#issuecomment-277048013>, or mute
the thread

**Comment by HenryCaiHaiying** [comment]
set system env:

SHYKO_MODE

Take a look at MaxwellConfig.java, you will see how to set it either in
system env or from command line arg.

**Comment by yogiGueta** [comment]
Ok, i did do that! thanks you!

**Comment by osheroff** [comment]
use the `binlog_connector` config setting instead -- SHYKO_MODE is just for tests and will go away

**Comment by osheroff** [comment]
Maxwell got gtid mode long ago
