### ISSUE TITLE
Out of order records with the Kinesis producer?

### ISSUE THREAD

**Issue by io41** [zendesk/maxwell#817]
I've been looking at using Kinesis over Kafka and came across these comments Kinesis config file:

```
...
# This setting provides coarse ordering among records - any two records will
# be reordered by no more than twice this amount (assuming no failures and
# retries and equal network latency).
...
RecordMaxBufferedTime = 100
```

That sounds like the order guarantees made by the binlog are lost. This made me nervous since order within a partition/shard is a most for many use cases. It seems [https://brandur.org/kinesis-order](https://brandur.org/kinesis-order) confirms my fears, assuming my basic Java reading ability of the Maxwell Kinesis producer is correct.

Is my reading of the situation correct?

If yes, the solution given by [https://brandur.org/kinesis-order](https://brandur.org/kinesis-order) would allow order guarantees to be made per partition without loosing the performance benefits of using the bulk API.

I guess the downsides would be:
- increased complexity, and
- a significant reduction in throughput when using only a few shards.

Possible Workarounds:
A client might be able to work around this by buffering messages on the receiving end, and comparing `ts`, `xid` and `position` values to verify relative order, though I don't see how to make that watertight.
The Kinesis Producer might be configured with `CollectionMaxCount=1`... though I'm not sure that behaves as I think it does, nor am I certain if this solves all issues, especially since it's called asynchronously.

**Comment by osheroff** [comment]
@io41 Sorry for the lag-time here.  Yeah, you're basically right, the kinesis-order solution (based on the partition key) can work, but really only when the partition-key is very fine-grained, ie when maxwell is configured with `--producer_partition_by=primary_key` -- otherwise you just end up reducing the throughput to 1 record per database.

Maxwell could maybe guarantee ordering on a per-primary-key basis regardless of the partition key chosen -- that way we could avoid the most catastrophic event, that a row with `id=2` pushes a `DELETE` event before an `INSERT`, or an `UPDATE` out-of-order.  Unfortunately this comes with its own set of performance issues; in my experience a single transaction may end up inserting a row and then updating it quite a few times.  In the PK-ordering-guarantee world, each modification to the row would need to be in a separate, serialized batch, and (assuming that Maxwell continues to process other rows) would also be out of sequence with the rest of the database statements.

In a word: it's a thorny problem.  GTIDs can help it resolve client-side.

**Comment by io41** [comment]
I suspected as much, but good to get confirmation. Thanks @osheroff
