### ISSUE TITLE
Recommended architecture for production (AWS)

### ISSUE THREAD

**Issue by caioreis** [zendesk/maxwell#994]
First of all, congratulations on this amazing project. I would like to know if there's any recommended architecture for production in AWS. How are you guys scaling maxwell, maybe using `AWS ECS` for specific tasks?

My goal with maxwell is to create an event publisher. My current flow is:

`EC2 running maxwell => Kinesis Stream => Kinesis Firehose => Lambda => SNS`

But it seems that an EC2 running maxwell is not resilient enough. I'm thinking about creating a lambda function to check on maxwell http stats each 5 seconds, for example.

Any opinions, cases and criticts are wellcome!

**Comment by ericwush** [comment]
How many db clusters are you replicating from? IMO you want to ensure one maxwell per db cluster at any time to avoid data duplicates. Especially when you use `ecs` or `kubernetes` make sure you recreate containers (kill the older ones before starting new ones) rather than rolling restart. Alternatively you can consider using lock mechanism, e.g. Consul lock.

**Comment by caioreis** [comment]
@ericwush I'm currently streaming from one cluster only, but with a high throughput (5k commits per minute). That's why I was considering using different tasks (maxwell instances) for different tables using the `include_only` option. Does that makes any sense?

**Comment by osheroff** [comment]
A single maxwell instance on a reasonable sized vm node (4 core) should handle 5k per minute no sweat, unless you’re talking about gigantic transactions.   I’m away from my benchmark numbers right now, will post later.

**Comment by caioreis** [comment]
@ericwush and @osheroff. Thanks for the responses. 

I'm actually more concerned about setting an auto healing and availability monitoring. 

And yes, I'm using maxwell kinesis producer :)

**Comment by osheroff** [comment]
so maxwell with `--metrics_type=http` exposes a few health-check and metric endpoints documented here: http://maxwells-daemon.io/monitoring/.  Not sure how this plays into AWS auto-heal, we've generally taken the position of "bring your own clustering", since kubernetes, consul, etc all seem to provide a good general solution.
